# frozen_string_literal: true

source 'https://rubygems.org'

# gem install vivlio-starter でローカルインストール済みであること
gem 'vivlio-starter'

# query-stream は公開済みバージョンを使用
gem 'query-stream', '~> 1.0.0'

# gem install vivlio-starter-pdf を実行したら、以下をコメントアウトしてください
gem 'vivlio-starter-pdf'