# frozen_string_literal: true

source 'https://rubygems.org'

# 電子書籍執筆システム
gem 'vivlio-starter'

# query-stream （データ展開）
gem 'query-stream'

# vivlio-starter-pdf をインストールしたい場合には、
# 以下をコメントアウトしてから、
# bundle install を実行してください。
# gem 'vivlio-starter-pdf'