##
## 章の配置
##

## まえがき
PREFACE:
  - 00-preface

## 本文
CHAPTERS:
  - 01-bonus
  - 02-top
  - 03-footer
  - 04-kiji
  - 05-about
  - 06-contact
  - 07-modaal
  - 08-shuffle-text
  - 09-sakura
  - 10-scroll-animation
  - 11-fixed-footer
  - 12-follow-menu
  - 13-mobile-menu
  - 14-muuri
  - 15-chart
  - 26-pwa

# ## 付録
APPENDICES:
  - 91-books
  - 92-links
  - 93-cheats

# ## あとがき
POSTFACE:
  - 99-postface

## 【Tips】
##
## ・付録やまえがきやあとがきがなければ、空にする。
##   例：
##
##     PREFACE:
##
##     CHAPTERS:
##       - 01-install.re
##
##     APPENDICES:
##
##     POSTFACE:
##
##
## ・第I部、第II部、…のように「部」を使うには、次のようにする。
##   （部タイトルの最後に半角の「:」をつけることに注意）
##
##     CHAPTERS:
##       - 初級編:
##           - 01-install.re
##           - 02-tutorial.re
##       - 中級編:
##           - 03-syntax.re
##           - 04-customize.re
##       - 上級編:
##           - 05-faq.re
##           - 06-bestpractice.re
##
