# ========================================
# ビルド対象にする章の指定
# ========================================
# 一部の章のみを対象としたい場合は、以下のように指定します。
  # - 11-install  # 拡張子(.md)は、省略できます。
  # - 12-tutorial
# CHAPTERS: 11-12, 13-15, 25 # 章番号のみでのカンマ区切り, 範囲指定も指定可能です。

## まえがき
PREFACE:
  - 00-preface

## 本文
CHAPTERS:
  - 【第一部：はじめる】:
      - 11-workflow
      - 12-quickstart
      - 13-new
  - 【第二部：書く】:
      - 21-markdown-tutorial
      - 22-chapter-management
      - 23-cross-reference
      - 24-querystream
  - 【第三部：整える】:
      - 31-lint
      - 32-metrics
      - 33-index-glossary
  - 【第四部：仕上げる】:
      - 41-book-yml
      - 42-frontispiece
      - 43-cover
      - 44-build
      - 45-utility
  - 【第五部：トラブルシューティング】:
      - 51-doctor
  - 【第六部：開発者のために】:
      - 61-developer

## 付録
APPENDICES:
  - 91-install
  - 92-pdf-read
  - 93-import
  - 94-sample

# ## あとがき
POSTFACE:
  - 99-postface

## 【Tips】
##
## ・付録やまえがきやあとがきがなければ、空にする。
##   例：
##
##     PREFACE:
##
##     CHAPTERS:
##       - 01-install.re
##
##     APPENDICES:
##
##     POSTFACE:
##
##
## ・第I部、第II部、…のように「部」を使うには、次のようにする。
##   （部タイトルの最後に半角の「:」をつけることに注意）
##
##     CHAPTERS:
##       - 初級編:
##           - 01-install.re
##           - 02-tutorial.re
##       - 中級編:
##           - 03-syntax.re
##           - 04-customize.re
##       - 上級編:
##           - 05-faq.re
##           - 06-bestpractice.re
##
