---
generated_at: '2026-02-07 20:32:57'
terms:
- term: ウェブサイト
  yomi: ウェブサイト
  definition: ''
  source: review
  approved_at: '2026-02-07 20:32:57'
  contexts:
  - chapter: 00-preface
    context: の基本操作ができる初心者の方を想定しています。中高生から社会人まで、ウェブサイトを作ってみたい方や、プログラミングに興味があって、なにかアプリを作ってみたい人の
