---
generated_at: '2026-04-07 03:52:26'
terms:
- term: PDF
  yomi: PDF
  flags: i
  definition: ''
  source: auto_extracted
  approved_at: '2026-04-07 03:52:12'
  pattern: "/\\bPDF\\b/"
  score: 365.0
  contexts:
  - chapter: 00-preface
    context: Vivlio Starter は、Markdown から高品質な電子書籍（PDF）を生成するための CLI ツールです。Vivliostyle
      をコアエンジンと
  - chapter: 01-quickstart
    context: Vivlio Starter をインストールして、最初の PDF を生成するまでの流れを体験します。難しいことは何もありません。コマンドをいくつ
  - chapter: 99-postface
    context: Markdown による原稿執筆から、HTML変換・目次生成・PDF化まで、書籍制作の一連の流れを習得するためのマニュアルです。 Vivlio
      S
  updated_at: '2026-04-07 03:52:26'
- term: Starter
  yomi: Starter
  flags: i
  definition: ''
  source: auto_extracted
  approved_at: '2026-04-07 03:52:12'
  pattern: "/\\bStarter\\b/"
  score: 530.0
  contexts:
  - chapter: 00-preface
    context: Vivlio Starter の世界へ！ 楽しい技術書づくりの世界へようこそ。 情報技術「IT」を日々利用して暮らしているわたくしたち。
      多くの先
  - chapter: 01-quickstart
    context: " :::{.chapter-lead} この章では、Vivlio Starter をインストールして、最初の PDF を生成するまでの流れを体験します。難しいこ"
  - chapter: 99-postface
    context: Vivlio Starter の使い方を学び、Markdown による原稿執筆から、HTML変換・目次生成・PDF化まで、書籍制作の一連の流れを習得す
  updated_at: '2026-04-07 03:52:26'
- term: Vivlio
  yomi: Vivlio
  flags: i
  definition: ''
  source: auto_extracted
  approved_at: '2026-04-07 03:52:12'
  pattern: "/\\bVivlio\\b/"
  score: 500.0
  contexts:
  - chapter: 00-preface
    context: Vivlio Starter の世界へ！ 楽しい技術書づくりの世界へようこそ。 情報技術「IT」を日々利用して暮らしているわたくしたち。
      多くの
  - chapter: 01-quickstart
    context: 'クイックスタート :::{.chapter-lead} この章では、Vivlio Starter をインストールして、最初の PDF '
  - chapter: 99-postface
    context: Vivlio Starter の使い方を学び、Markdown による原稿執筆から、HTML変換・目次生成・PDF化まで、書籍制作の一連の流れを習得
  updated_at: '2026-04-07 03:52:26'
