---
rejected_at: '2026-02-08 02:44:26'
rejected_terms:
- term: ページ
  yomi: ぺーじ
  rejected_at: '2026-02-08 01:56:59'
  score: 209.1
- term: ウェブ
  yomi: ウェブ
  rejected_at: '2026-02-08 01:57:50'
  score: 231.2
