---
rejected_at: '2026-08-04 03:11:21'
rejected_terms:
- term: Starter
  yomi: Starter
  rejected_at: '2026-07-05 21:00:15'
  score: 2146.8
- term: Vivlio
  yomi: Vivlio
  rejected_at: '2026-07-05 21:00:15'
  score: 2074.0
- term: ヒント
  yomi: ひんと
  rejected_at: '2026-07-05 21:00:15'
  score: 369.6
- term: コピー
  yomi: こぴー
  rejected_at: '2026-07-05 21:00:15'
  score: 368.4
- term: サイズ
  yomi: さいず
  rejected_at: '2026-07-05 21:00:15'
  score: 745.2
- term: スキップ
  yomi: すきっぷ
  rejected_at: '2026-07-05 21:00:15'
  score: 939.8
- term: ジョン
  yomi: じょん
  rejected_at: '2026-07-05 21:00:15'
  score: 313.5
- term: チェック
  yomi: ちぇっく
  rejected_at: '2026-07-05 21:00:15'
  score: 1510.9
- term: ベース
  yomi: べーす
  rejected_at: '2026-07-05 21:00:15'
  score: 317.5
- term: g
  yomi: g
  rejected_at: '2026-07-05 21:00:15'
- term: Step
  yomi: Step
  rejected_at: '2026-07-05 21:00:15'
  score: 1790.0
- term: Command
  yomi: Command
  rejected_at: '2026-07-05 21:00:15'
  score: 651.3
- term: Line
  yomi: Line
  rejected_at: '2026-07-05 21:00:15'
  score: 371.6
- term: Mode
  yomi: Mode
  rejected_at: '2026-07-05 21:00:15'
  score: 957.1
- term: VIEW
  yomi: VIEW
  rejected_at: '2026-07-05 21:00:15'
  score: 269.2
- term: Hz
  yomi: Hz
  rejected_at: '2026-07-16 20:06:30'
- term: eV
  yomi: eV
  rejected_at: '2026-07-16 20:06:30'
- term: オプション
  yomi: おぷしょん
  rejected_at: '2026-08-03 23:14:32'
- term: 技術書
  yomi: ぎじゅつしょ
  rejected_at: '2026-08-03 23:14:32'
- term: コマンド
  yomi: こまんど
  rejected_at: '2026-08-03 23:14:32'
- term: コード
  yomi: こーど
  rejected_at: '2026-08-03 23:14:32'
- term: コードブロック
  yomi: こーどぶろっく
  rejected_at: '2026-08-03 23:14:32'
- term: ツール
  yomi: つーる
  rejected_at: '2026-08-03 23:14:32'
- term: ディレクトリ
  yomi: でぃれくとり
  rejected_at: '2026-08-03 23:14:32'
- term: データ
  yomi: でーた
  rejected_at: '2026-08-03 23:14:32'
- term: ファイル
  yomi: ふぁいる
  rejected_at: '2026-08-03 23:14:32'
- term: ブロック
  yomi: ぶろっく
  rejected_at: '2026-08-03 23:14:32'
- term: プロジェクト
  yomi: ぷろじぇくと
  rejected_at: '2026-08-03 23:14:32'
- term: ページ
  yomi: ぺーじ
  rejected_at: '2026-08-03 23:14:32'
- term: エンジン
  yomi: えんじん
  rejected_at: '2026-08-03 23:14:32'
- term: システム
  yomi: しすてむ
  rejected_at: '2026-08-03 23:14:32'
- term: フォーマット
  yomi: ふぉーまっと
  rejected_at: '2026-08-03 23:14:32'
- term: フロー
  yomi: ふろー
  rejected_at: '2026-08-03 23:14:32'
- term: 印刷用
  yomi: いんさつよう
  rejected_at: '2026-08-03 23:14:32'
- term: Apple
  yomi: Apple
  rejected_at: '2026-08-03 23:14:32'
- term: Books
  yomi: Books
  rejected_at: '2026-08-03 23:14:32'
- term: カバー
  yomi: かばー
  rejected_at: '2026-08-03 23:14:32'
- term: ステップ
  yomi: すてっぷ
  rejected_at: '2026-08-03 23:14:32'
- term: Markdown
  yomi: Markdown
  rejected_at: '2026-08-03 23:16:08'
- term: PDF
  yomi: PDF
  rejected_at: '2026-08-03 23:16:08'
- term: インストール
  yomi: いんすとーる
  rejected_at: '2026-08-03 23:16:08'
- term: ビルド
  yomi: ビルド
  rejected_at: '2026-08-03 23:16:08'
- term: カスタマイズ
  yomi: かすたまいず
  rejected_at: '2026-08-04 03:11:20'
- term: デフォルト
  yomi: でふぉると
  rejected_at: '2026-08-04 03:11:20'
- term: レベル
  yomi: れべる
  rejected_at: '2026-08-04 03:11:20'
- term: インライン
  yomi: いんらいん
  rejected_at: '2026-08-04 03:11:20'
- term: スキャン
  yomi: すきゃん
  rejected_at: '2026-08-04 03:11:20'
- term: カラー
  yomi: からー
  rejected_at: '2026-08-04 03:11:20'
- term: Playwright
  yomi: Playwright
  rejected_at: '2026-08-04 03:11:20'
- term: Samovar
  yomi: Samovar
  rejected_at: '2026-08-04 03:11:20'
- term: テーマ
  yomi: てーま
  rejected_at: '2026-08-04 03:11:20'
  score: 288.7
- term: 自動生成
  yomi: じどうせいせい
  rejected_at: '2026-08-04 03:11:20'
  score: 252.4
- term: スタイル
  yomi: すたいる
  rejected_at: '2026-08-04 03:11:20'
  score: 246.0
- term: バージョン
  yomi: ばーじょん
  rejected_at: '2026-08-04 03:11:20'
  score: 260.5
- term: セクション
  yomi: せくしょん
  rejected_at: '2026-08-04 03:11:20'
  score: 254.2
- term: ファイル名
  yomi: ふぁいるめい
  rejected_at: '2026-08-04 03:11:20'
  score: 260.7
- term: ルール
  yomi: るーる
  rejected_at: '2026-08-04 03:11:20'
  score: 274.1
- term: レイアウト
  yomi: れいあうと
  rejected_at: '2026-08-04 03:11:20'
  score: 251.4
