---
path: contents/31-netlify.md
title: ウェブサイトの公開
chapter_num: 31
chars: 6424
warning:
sections:
- title: Netlify（ネットリファイ） でウェブサイトを公開する
  chars: 300
  warning: 加筆検討
- title: Netlify（ネットリファイ） に会員登録する
  chars: 1701
  warning:
- title: Netlify（ネットリファイ） の利用方法
  chars: 4131
  warning: やや長い
basic_stats:
  chars: 6683
  chars_without_newline: 6424
  lines: 259
  sentences: 127
  avg_sentence_chars: 49.275590551181104
  clauses: 85
  avg_clause_chars: 74.56470588235294
  commas: 84
vocabulary_stats:
  kanji_ratio: 13.58089260808926
  avg_word_length: 2.240867579908676
  ttr: 0.20662100456621005
  total_tokens: 2628
  unique_tokens: 543
  kanji_char_count: 779
  total_char_count: 5736
  total_word_length: 5889
  tokens_map:
    ウェブサイト: 12
    の: 78
    公開: 26
    従来: 1
    "、": 84
    を: 102
    する: 137
    ため: 6
    に: 63
    は: 34
    サーバー: 1
    と: 39
    呼ぶ: 2
    れる: 19
    コンピュータ: 2
    適宜: 2
    様々: 7
    だ: 16
    設定: 8
    施す: 1
    運用: 3
    て: 41
    くる: 2
    ます: 99
    た: 30
    "。": 107
    安全: 1
    それなり: 1
    伎倆: 1
    が: 56
    求める: 1
    られる: 6
    もの: 2
    です: 28
    こうした: 1
    中: 1
    台頭: 1
    各種: 1
    ホスティングサービス: 1
    簡単: 3
    そして: 1
    安価: 1
    こと: 21
    できる: 18
    ここ: 9
    で: 25
    Netlify: 20
    "（": 19
    ネットリファイ: 5
    "）": 15
    ご: 3
    紹介: 2
    "「": 45
    構築: 1
    最速: 1
    方法: 5
    "」": 40
    いる: 21
    よう: 9
    HTML: 1
    "/": 4
    CSS: 1
    JavaScript: 1
    配信: 6
    サイト: 34
    https: 1
    "://": 1
    app: 3
    ".": 47
    netlify: 35
    com: 1
    drop: 4
    ブラウザ: 3
    開く: 5
    一式: 2
    直接: 1
    アップ: 1
    ロード: 1
    だけ: 3
    全: 1
    世界: 1
    じゃん: 1
    ける: 2
    ゲーム: 2
    例えば: 1
    study: 2
    フォルダ: 6
    作成: 5
    ある: 9
    ば: 1
    この: 6
    ドラッグ: 7
    "＆": 7
    ドロップ: 7
    世界中: 2
    '1': 1
    時間: 1
    "![](": 34
    draganddrop: 1
    webp: 34
    ")": 42
    会員: 6
    登録: 10
    利点: 1
    小規模: 1
    利用: 7
    "[^": 2
    '101': 2
    "]": 1
    無料: 2
    サービス: 1
    ぬ: 1
    とも: 1
    可能: 1
    により: 1
    永久: 1
    的: 1
    名: 12
    好き: 1
    名前: 4
    変更: 6
    問い合わせ: 1
    フォーム: 1
    投稿: 1
    メール: 4
    通知: 1
    など: 5
    機能: 1
    使える: 2
    なる: 7
    ので: 13
    お: 2
    薦める: 1
    また: 2
    バージョン: 1
    管理: 1
    システム: 1
    として: 2
    Git: 5
    ギット: 1
    や: 4
    リポジトリサービス: 1
    GitHub: 4
    ギットハブ: 3
    "）,": 4
    GitLab: 2
    ギットラボ: 2
    Bitbucket: 2
    ビット: 2
    バケット: 2
    使う: 7
    方: 1
    より: 1
    便利: 1
    連携: 2
    "]:": 1
    Starter: 1
    プラン: 3
    "(": 11
    転送: 1
    量: 1
    ":": 2
    '100': 2
    GB: 2
    月: 1
    まで: 10
    容量: 2
    桜: 1
    吹雪: 1
    約: 1
    '700': 1
    kB: 1
    単純: 1
    計算: 1
    毎日: 1
    '5000': 1
    人: 2
    見る: 2
    有料: 1
    へ: 5
    移行: 1
    考える: 1
    良い: 2
    う: 6
    アクセス: 2
    '20': 1
    '21': 2
    右: 3
    上: 5
    青い: 2
    Sign: 4
    up: 3
    ボタン: 13
    押す: 15
    次: 7
    画面: 19
    "<": 4
    br: 4
    ">": 4
    それぞれ: 1
    アカウント: 1
    一番: 2
    下: 5
    Email: 1
    a: 10
    メールアドレス: 3
    パスワード: 2
    入力: 9
    '22': 1
    表示: 13
    送る: 1
    確認: 4
    くれる: 1
    '23': 1
    ソフト: 1
    から: 3
    届く: 1
    緑色: 1
    Verify: 2
    email: 3
    不正: 1
    ミス: 1
    対策: 1
    為: 2
    用いる: 2
    仕組み: 1
    者: 2
    続き: 1
    行う: 5
    Nice: 1
    to: 12
    meet: 1
    you: 7
    "!": 1
    Let: 1
    "'": 3
    s: 3
    get: 1
    acquainted: 1
    ".(": 2
    よろしく: 1
    お願い: 1
    "！": 1
    知り合い: 1
    挨拶: 1
    有る: 1
    How: 1
    ar: 1
    your: 7
    planning: 1
    use: 3
    "?(": 4
    予定: 1
    "？)": 4
    尋ねる: 1
    Personal: 3
    Work: 1
    School: 1
    Client: 1
    今回: 1
    個人: 2
    ")」": 5
    選ぶ: 3
    '24': 1
    What: 3
    kind: 1
    of: 3
    site: 12
    do: 1
    want: 2
    build: 1
    first: 1
    まず: 1
    どんな: 1
    作る: 1
    たい: 6
    か: 7
    質問: 1
    いくつ: 1
    選択肢: 2
    おく: 1
    best: 1
    describes: 1
    role: 1
    あなた: 1
    役割: 1
    何: 3
    Freelancer: 1
    Hobby: 2
    Developer: 2
    Other: 1
    趣味: 1
    開発: 2
    最後: 2
    is: 1
    the: 4
    name: 6
    team: 2
    チーム: 3
    問う: 1
    People: 1
    who: 1
    for: 2
    personal: 1
    work: 1
    often: 1
    project: 2
    or: 1
    their: 1
    own: 1
    プロジェクト: 3
    自分: 1
    多い: 1
    注釈: 1
    自身: 1
    好み: 1
    なさる: 1
    くださる: 6
    Continue: 1
    deploy: 3
    デプロイ: 9
    続ける: 2
    これ: 1
    完了: 5
    ログイン: 4
    左側: 1
    Log: 3
    in: 4
    '25': 1
    '26': 1
    等: 2
    も: 4
    with: 1
    '27': 1
    Team: 6
    overview: 8
    '30': 2
    b: 1
    配備: 5
    "・": 7
    Weblio: 1
    英和: 1
    辞典: 1
    よる: 1
    "〈": 1
    部隊: 1
    兵力: 1
    "〉": 1
    展開: 1
    "，": 1
    配置: 1
    意味: 2
    英単語: 1
    IT: 1
    分野: 1
    ソフトウェア: 1
    実用: 1
    供する: 1
    用語: 1
    デプロイ・: 1
    Sites: 5
    欄: 3
    今: 9
    まだ: 1
    ない: 4
    代わり: 1
    案内: 1
    場合: 4
    Import: 2
    an: 1
    existing: 1
    既存: 1
    取り込む: 2
    ")「": 1
    from: 1
    手動: 1
    中央: 3
    Drag: 3
    and: 3
    output: 3
    folder: 3
    here: 3
    出力: 3
    納める: 1
    しばらく: 1
    steady: 4
    "-": 14
    paletas: 4
    '13': 4
    bb: 4
    '99': 4
    という: 1
    Get: 1
    Started: 1
    行動: 1
    移る: 1
    '31': 1
    活動: 1
    状況: 2
    一覧: 5
    遷移: 5
    '32': 1
    付ける: 1
    命名: 1
    改名: 1
    クリック: 18
    '33': 1
    Site: 6
    settings: 3
    に関する: 3
    行える: 1
    もちろん: 1
    名称: 2
    '34': 1
    出来る: 7
    Change: 1
    '35': 1
    新しい: 3
    アルファベット: 1
    数字: 1
    他: 1
    "-(": 1
    ハイフン: 1
    終える: 1
    Save: 1
    '37': 1
    joyful: 6
    janken: 7
    '38': 1
    '01': 1
    手元: 1
    動作: 1
    じゃ: 1
    ん: 2
    今や: 1
    人々: 1
    更新: 5
    手順: 3
    左上: 3
    ロゴ: 3
    マーク: 3
    '61': 1
    のみ: 2
    '62': 1
    Deploys: 2
    '63': 1
    Need: 1
    update: 1
    "?": 3
    必要: 1
    "？": 3
    '64': 1
    追加: 2
    加える: 1
    別: 1
    思う: 2
    '71': 1
    Want: 1
    new: 1
    without: 1
    connectiong: 1
    接続: 1
    '72': 1
    削除: 8
    何らかの: 1
    理由: 1
    '81': 1
    '82': 1
    '83': 1
    Danger: 1
    one: 1
    '84': 1
    Delete: 2
    this: 3
    '85': 1
    注意: 3
    書き: 2
    text: 1
    Are: 1
    absolutely: 1
    sure: 1
    delete: 2
    If: 1
    have: 1
    submitted: 1
    support: 1
    request: 1
    about: 1
    ",": 1
    it: 2
    will: 1
    be: 2
    difficult: 1
    Support: 1
    help: 1
    debug: 1
    situation: 1
    if: 1
    Remember: 1
    remove: 1
    any: 1
    DNS: 2
    records: 1
    that: 1
    point: 1
    URL: 2
    This: 1
    action: 1
    cannot: 1
    undone: 1
    本当に: 1
    いい: 1
    について: 1
    サポート: 2
    リクエスト: 1
    提出: 1
    しまう: 2
    デバッグ: 1
    助ける: 1
    難しい: 1
    指す: 1
    レコード: 1
    忘れる: 1
    操作: 1
    元: 1
    戻せる: 1
    了承: 1
    Type: 1
    confirm: 1
    書く: 1
    '86': 1
    押せる: 1
    復活: 1
    '87': 1
    ログアウト: 2
    Ｍ: 1
    によって: 1
    変わる: 1
    いろいろ: 1
    メニュー: 1
    out: 1
    終了: 1
    '90': 1
readability:
  score: 31.42824157963518
  label: Standard
