# Minimal Re:VIEW config for converting source_material/contents/*.re to Markdown
inherit:
  - ../config/config-starter.yml
review_version: 2.0
bookname: source_material
language: ja
starter:
  part_startnumber: 1
  chapter_startnumber: 1

debug: true
ignore-errors: true

# Use catalog.yml in this directory
catalogfile: catalog.yml

# catalog.yml には 'contents/11-life.re' のようにパスを記述しているので
# contentdir はルート (.) のままでよい
contentdir: .
